feat: Penrose editable svgs
penrose/penrose pull request #1171
Opened 2022-12-10 00:40 UTC by lmxlucy

# Description

Related issue/PR: #1129 

Provide editability of any (SVG) diagram created in Penrose.
1. SVGs exported from Penrose contain (in metadata) the entire source code used to generate the diagram (Domain, Style, and Substance), along with the seed and software version.
2. The Penrose IDE can directly import an SVG, and automatically import this metadata.

# Implementation strategy and design decisions

Include a high-level summary of the implementation strategy and list important design decisions made, if any.

# Examples with steps to reproduce them

# Checklist

- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new ESLint warnings
- [x] I have reviewed any generated changes to the `diagrams/` folder

2022-12-10 03:12 UTC, wodeni reviewed
LGTM overall! Thanks again for submitting the PR 🎉!

I only have a few minor comments that might improve the UX a little bit. I tested the new feature locally and everything seems to run very smoothly. For testing, it might be useful to start adding some tests to `editor` for this (e.g. serializing all diagrams from the registry and loading them again). This might require a bit more changes and is probably worth another PR.

2022-12-10 03:12 UTC, wodeni commented on packages/editor/src/components/SvgUploader.tsx
> +      toast.success("Sucessfully uploaded SVG to editor");
Since the SVG should be renderable, we can directly call `compileDiagram` after upload. Can you try using `useCompileDiagram` from `state/callbacks`?

2022-12-10 03:12 UTC, wodeni commented on packages/editor/src/components/SvgUploader.tsx
> +      const styElem = xmlDoc.getElementsByTagName("sty");
I don't see the `variation` being used here. To faithfully recreate the uploaded SVG, the `variation` needs to be the same as well. You can use `setDiagramMetadata` from `diagramMetadataSelector` to set the metadata.

2022-12-10 18:34 UTC, lmxlucy commented on packages/core/src/renderer/Renderer.ts
> +import { sub } from "engine/AutodiffFunctions";
No, I will delete this

2022-12-10 18:34 UTC, lmxlucy commented on packages/editor/src/components/DiagramPanel.tsx
> + * TODO: Given an SVG, program triple, and version and variation strings,
Yes, I will delete the TODO

2022-12-11 21:34 UTC, wodeni requested changes
Thanks for cleaning the diff! Small comments on variation loading below.

2022-12-11 21:34 UTC, wodeni commented on packages/editor/src/components/SvgUploader.tsx
> +        variation: diagramMetadata.variation,
I think you'll need to read the variation from the SVG file instead of using the one from the current workspace.

2022-12-11 21:34 UTC, wodeni commented on packages/editor/src/components/DiagramPanel.tsx
> +  const variation = document.createElementNS(
(basically this field will need to be loaded in the uploader)

2022-12-11 21:34 UTC, wodeni commented on packages/editor/src/components/SvgUploader.tsx
> +      const styElem = xmlDoc.getElementsByTagName("sty");
Also bumping this comment

2022-12-13 04:34 UTC, wodeni requested changes
Great! `variation` works correctly now. I think it'd be great if we auto-compile uploaded diagrams as a finishing touch. Also a small comment on calls to `trim`, not a functional issue, just want to future-proof this.

2022-12-13 04:34 UTC, wodeni commented on packages/editor/src/components/SvgUploader.tsx
> +        variation: variationElem[0].textContent ?? "".trim(),
My understanding is you wanted to `trim` the whole thing?

```suggestion
        variation: (variationElem[0].textContent ?? "").trim(),
```

2022-12-13 04:34 UTC, wodeni commented on packages/editor/src/components/SvgUploader.tsx
> +        contents: styElem[0].textContent ?? "".trim(),
same `trim` issue here

2022-12-13 04:34 UTC, wodeni commented on packages/editor/src/components/SvgUploader.tsx
> +        contents: subElem[0].textContent ?? "".trim(),
same `trim` issue here

2022-12-13 04:34 UTC, wodeni commented on packages/editor/src/components/SvgUploader.tsx
> +      toast.success("Sucessfully uploaded SVG to editor");
bumping this comment

2022-12-13 17:34 UTC, wodeni commented
> > I think it'd be great if we auto-compile uploaded diagrams as a finishing touch.
> 
> 
> 
> I tried to auto-compile diagram after upload. I tried `compileDiagram` inside `handleChange` both inside(after current workspace is updated with uploaded trios) and after `reader.onload` but diagram was not compiled and no error was displayed. I also did not find other events appropriate for `compileDiagram`. I am not sure what the problem is. Do you have any ideas on what to do? 
> 
> 

My guess is that you did not `await` for `compileDiagram`. The function is asynchronous (for retrieving math labels and resolving images mostly) and callers need to wait for it to complete. Your `onload` will need to be async too probably.

2022-12-13 18:01 UTC, lmxlucy commented
> > > I think it'd be great if we auto-compile uploaded diagrams as a finishing touch.
> > 
> > 
> > I tried to auto-compile diagram after upload. I tried `compileDiagram` inside `handleChange` both inside(after current workspace is updated with uploaded trios) and after `reader.onload` but diagram was not compiled and no error was displayed. I also did not find other events appropriate for `compileDiagram`. I am not sure what the problem is. Do you have any ideas on what to do?
> 
> My guess is that you did not `await` for `compileDiagram`. The function is asynchronous (for retrieving math labels and resolving images mostly) and callers need to wait for it to complete. Your `onload` will need to be async too probably.

Thank you!! Good to go now!!

2022-12-13 19:09 UTC, wodeni requested changes
Final thing: you can simply `await` the function call. Looking forward to having this in `main`!

2022-12-13 19:09 UTC, wodeni commented on packages/editor/src/components/SvgUploader.tsx
> +      await new Promise(compileDiagram);
```suggestion
      await compileDiagram();
```

2022-12-14 02:48 UTC, lmxlucy commented
> Final thing: you can simply `await` the function call. Looking forward to having this in `main`!

Thank you!

2022-12-14 06:13 UTC, wodeni approved these changes
Wonderful 💯! Merging after CI passes.

2022-12-14 06:16 UTC, wodeni commented
Looks like `format` is not passing. @lmxlucy do you mind running `yarn format` and push again?

2022-12-14 13:52 UTC, wodeni commented
Looks like something is off with your prettier configuration. Be sure to run `yarn format` at the repo root, and do not use a global installation of prettier (I guess that's the reason why the diffs have conflicts).

2022-12-14 19:52 UTC, wodeni commented
Looks like we have `prettier` set at `2.2.1`, not `2.3.0`. 
https://github.com/penrose/penrose/blob/3ae696e252fb76624ebc407e6aa57d5d24c9c4a9/package.json#L37

Might wanna [reset your build](https://github.com/penrose/penrose/blob/main/CONTRIBUTING.md#refresh-build)?

2022-12-14 20:22 UTC, lmxlucy commented
> Looks like we have `prettier` set at `2.2.1`, not `2.3.0`.
> 
> https://github.com/penrose/penrose/blob/3ae696e252fb76624ebc407e6aa57d5d24c9c4a9/package.json#L37
> 
> Might wanna [reset your build](https://github.com/penrose/penrose/blob/main/CONTRIBUTING.md#refresh-build)?

I rebuilt and format again. But my prettier version is still 2.2.1

2022-12-14 20:36 UTC, lmxlucy commented
> Looks like we have `prettier` set at `2.2.1`, not `2.3.0`.
> 
> https://github.com/penrose/penrose/blob/3ae696e252fb76624ebc407e6aa57d5d24c9c4a9/package.json#L37
> 
> Might wanna [reset your build](https://github.com/penrose/penrose/blob/main/CONTRIBUTING.md#refresh-build)?

I changed my prettier version to 2.3.0 and cleaned my build. But there seem to still be conflicts

2022-12-14 20:41 UTC, wodeni commented
> > Looks like we have `prettier` set at `2.2.1`, not `2.3.0`.
> 
> > 
> 
> > https://github.com/penrose/penrose/blob/3ae696e252fb76624ebc407e6aa57d5d24c9c4a9/package.json#L37
> 
> > 
> 
> > Might wanna [reset your build](https://github.com/penrose/penrose/blob/main/CONTRIBUTING.md#refresh-build)?
> 
> 
> 
> I changed my prettier version to 2.3.0 and cleaned my build. But there seem to still be conflicts

To clarify: `2.2.1` is the expected version. Try downgrading or refreshing the build again?

2022-12-14 22:20 UTC, merged