refactor: split the registry into individual trio JSONs
penrose/penrose pull request #1387
Opened 2023-05-12 17:12 UTC by wodeni

# Description

Resolves #issue.

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

# Implementation strategy and design decisions

Include a high-level summary of the implementation strategy and list important design decisions made, if any.

# Examples with steps to reproduce them

# Checklist

- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have reviewed any generated registry diagram changes

# Open questions

Questions that require more discussion or to be addressed in future development:

2023-05-15 15:18 UTC, samestep reviewed
I'm guessing this wasn't meant to be marked as ready for review but here are a few random comments in case they're helpful at all (guessing not)

2023-05-15 19:32 UTC, wodeni commented on packages/roger/types.ts
> -  extra?: unknown;
This was specific to the artifacts static page, so I basically deprecated all metadata related to those.

2023-05-15 19:41 UTC, samestep commented
The CI `readme` and `registry` jobs are failing; could you fix those?

2023-05-15 19:42 UTC, samestep requested changes
Also it looks like you missed a couple other accidental `CHANGELOG.md` changes:

2023-05-15 19:42 UTC, samestep commented on packages/core/CHANGELOG.md
here

2023-05-15 19:42 UTC, samestep commented on packages/roger/CHANGELOG.md
and here

2023-05-16 01:54 UTC, samestep commented
Looking at the registry diff, I see that most of them just changed the `id` prefix from `automator-` to `roger-`, but others actually have visual changes to the diagram, such as `call-directed-graph-directed-multigraph.svg`. Any idea what's causing that?

2023-05-16 03:49 UTC, wodeni commented
> Looking at the registry diff, I see that most of them just changed the `id` prefix from `automator-` to `roger-`, but others actually have visual changes to the diagram, such as `call-directed-graph-directed-multigraph.svg`. Any idea what's causing that?

I'm really not sure. This is probably not related to the variation itself. Can't imagine `tsx` making a difference here.

2023-05-16 18:21 UTC, samestep requested changes
Looks great overall! Could you either update `CONTRIBUTING.md` or add back an `install-global` script to `@penrose/roger`?

2023-05-16 18:25 UTC, samestep commented on packages/core/CHANGELOG.md
> +- staged diagram generation in roger ([#610](https://github.com/penrose/penrose/issues/610)) ([3de4a31](https://github.com/penrose/penrose/commit/3de4a31543ddac80ed24274fde66d9e84304daa1))
```suggestion
- staged diagram generation in automator ([#610](https://github.com/penrose/penrose/issues/610)) ([3de4a31](https://github.com/penrose/penrose/commit/3de4a31543ddac80ed24274fde66d9e84304daa1))
```

2023-05-16 18:26 UTC, samestep commented on packages/roger/CHANGELOG.md
Can you revert your changes to this file? Unless your intention was to combine this with the `@penrose/automator` changelog and you're doing something clever here...

2023-05-16 18:37 UTC, samestep commented on packages/roger/index.ts
> +import {
```suggestion
import "global-jsdom/register"; // must be first

import yargs from "yargs";
import { hideBin } from "yargs/helpers";
import {
```

2023-05-16 18:40 UTC, wodeni commented on packages/roger/CHANGELOG.md
The intention is to retain the `automator` CHANGELOG, as it make up the majority of `roger` code.

2023-05-16 18:47 UTC, samestep commented on .prettierignore
> +/packages/roger/out/
Alphabetize pls 😛

2023-05-16 18:51 UTC, samestep approved these changes

2023-05-16 18:59 UTC, merged