[WIP] feat: type-change implemented for synthesizer
penrose/penrose pull request #585
Opened 2021-06-09 04:40 UTC by hsharriman

# Description
Added additional edit mutation to synthesizer, specifically **type-change**. For example, `Collinear(A,B,C)` -> `Triangle t := mkTriangle(A,B,C)`

Related issue/PR: # (issue/PR)

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
* Implemented type-change edit functionality for synthesizer
* Implemented cascading-delete functionality for synthesizer (if a ref is deleted, remove all other occurrences of the ref in the AST)
* Created additional substance file to use for testing the type-change and/or cascading delete functionality
* A bit of refactoring of current synthesizer code for modularity

# Implementation strategy and design decisions

Include a high-level summary of the implementation strategy and list important design decisions made, if any.

# Examples with steps to reproduce them
Run `yarn tri-example` from `packages/synthesizer`, with the current implementation you will likely run into a runtime error caused by a bug I am currently trying to remove :) There will also be examples of cascading deletions in play.

# Checklist
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ x] My changes generate no new warnings
- [ x] New and existing tests pass locally using `yarn test`
- [ ] I ran `yarn docs` and there were no errors when generating the HTML site
- [ x] My code follows the style guidelines of this project (e.g.: no ESLint warnings)

# Notes to self before submitting:
-[ ] remove commented out blocks when everything is working
-[ ] revert/make a new config file for testing the type-change instead of editing the current one
-[ ] check TODOs
-[ ] add comments

# Open questions
The caching issue is interfering with the TypeChange testing at the moment so I would really like to get it resolved in this PR.  Here's a list of operations performed in a particular program. You can see that `swapArgs` affects `Collinear`, but then when the synthesizer tries to delete `Collinear` later on, it can't find the updated reference in the AST (I do believe that printing out the statements indicates that the new version is in fact in the AST so it's a bit odd. It is also pretty late so I might have a different idea in the morning):
```
ℹ Operations:                                   substance synthesizer 19:45:54
 Add Point p0
Add Point p1
Add Point p2
Add Point p3
Add Rectangle r0
Add r0 := MkRectangle(p0, p1, p2, p3)
Add Collinear(p3, p1, p0)
Replace Collinear(p3, p1, p0) by Collinear(p3, p0, p1)     # swapArgs called here
Add p02 p4
Add p02 p4
Add p02 := TriangleVertex(p3, p1, p0)
Delete Collinear(p3, p0, p1)    # runtime error thrown here, cannot find Collinear(p3,p0,p1)
Add p02 p5
Add p02 p5
Add p02 := MkTriangle(p3, p0, p1)
Add AutoLabel All
```
Questions that require more discussion or to be addressed in future development:

2021-06-10 01:39 UTC, hsharriman commented
When I ran the pre-commit checks, I got these warnings I haven't seen before. Do I need to worry about these?
```
@penrose/core: $ nearleyc src/parser/Domain.ne > src/parser/DomainParser.ts && nearleyc src/parser/Substance.ne > src/parser/SubstanceParser.ts && nearleyc src/parser/Style.ne > src/parser/StyleParser.ts
@penrose/core: $ jest --watchAll=false
@penrose/core: PASS src/parser/SubstanceParser.test.ts
@penrose/core: PASS src/compiler/Domain.test.ts
@penrose/core: PASS src/parser/DomainParser.test.ts
@penrose/core: PASS src/compiler/Style.test.ts
@penrose/core: PASS src/analysis/SubstanceAnalysis.test.ts
@penrose/core: PASS src/compiler/Substance.test.ts
@penrose/core: PASS src/__tests__/mathtransform.test.ts
@penrose/core: PASS src/parser/StyleParser.test.ts
@penrose/core: PASS src/synthesis/Synthesizer.test.ts
@penrose/core: PASS src/__tests__/overall.test.ts (14.936 s)
@penrose/core:   ● Console
@penrose/core:     console.log
@penrose/core:       [warn] [top level] State is not prepared for energy evaluation. Call `prepareState` to initialize the optimization problem first.
@penrose/core:       at formatLogObj.width (../../node_modules/consola/dist/consola.js:1:16017)
@penrose/core:     console.log
@penrose/core:       [warn] [top level] State is not prepared for energy evaluation. Call `prepareState` to initialize the optimization problem first.
@penrose/core:       at formatLogObj.width (../../node_modules/consola/dist/consola.js:1:16017)
@penrose/core: Test Suites: 10 passed, 10 total
@penrose/core: Tests:       136 passed, 136 total
@penrose/core: Snapshots:   0 total
@penrose/core: Time:        16.164 s
@penrose/core: Ran all test suites.
```

2021-06-10 03:18 UTC, hsharriman commented on packages/core/src/synthesis/Synthesizer.ts
> +  removeID = (typeStr: string, id: Identifier) => {
When a declaration is deleted, the `declaredIDs` need to be updated to reflect it. This adds the capability to remove an Identifier from the list of valid IDs

2021-06-10 03:24 UTC, hsharriman commented on packages/core/src/synthesis/Synthesizer.ts
> +        return s.tag === subType && s.type.name.value === name;
This function wasn't matching Decl statements before

2021-06-10 15:01 UTC, wodeni requested changes
Looking great! The cascading delete seems to work pretty well. As always, the code is well documented and easy to follow. I also liked that you attempted to refactor and reuse the code from the previous PR. All great engineering practices 👍 . My main thoughts are:

* It's a more reusable design if we can write the code transformation functions (e.g. `replaceName`, `changeType`, etc) without the randomness. In principle, we want to contain the randomness in the `Synthesis` module only, so we can test the analysis stuff and control the randomness easier.
* There's a bit of redundancy in the decl matching functions. It'll take some discussion and design to arrive at a clean API for querying `Env`. See my comments about `findMatches`/`findStmt`   
* Some usual "write this as a pure function" suggestions in the detailed comments

2021-06-11 14:35 UTC, wodeni approved these changes

2021-06-11 14:37 UTC, merged