feat: adding browser for synthesizer
penrose/penrose pull request #640
Opened 2021-08-05 17:23 UTC by hsharriman

# Description

Related issue/PR: # (issue/PR)

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

# Implementation strategy and design decisions

Include a high-level summary of the implementation strategy and list important design decisions made, if any.

# Examples with steps to reproduce them

# Checklist

- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] New and existing tests pass locally using `yarn test`
- [ ] I ran `yarn docs` and there were no errors when generating the HTML site
- [ ] My code follows the style guidelines of this project (e.g.: no ESLint warnings)

# Open questions

Questions that require more discussion or to be addressed in future development:

2021-08-17 16:02 UTC, wodeni requested changes
Great job! I just went through the code and dropped some comments below. I'll play around with the UI a bit later :D.

Seems like the CI is failing for some reason. Can you try running `yarn build` locally and see what errors you are getting? I'm guessing something is off with `react-scripts`?

2021-08-17 17:48 UTC, hsharriman commented on packages/synthesizer-ui/src/components/Gridbox.tsx
> +  computeEnergy = async (optimizedState: IState) => {
Hmm, I tried doing this but the reference to the compiled state got lost when it was passed to the mutated programs (which sounds like an implementation issue), I could give it another shot though

2021-08-17 17:54 UTC, wodeni commented on packages/synthesizer-ui/src/components/Gridbox.tsx
> +  computeEnergy = async (optimizedState: IState) => {
Yeah not high-priority. There might be some weird side effects of the CIEE computation tbh. Let's table this.

2021-08-19 12:28 UTC, wodeni approved these changes
💯

2021-08-19 12:28 UTC, merged